ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - before: cd playground/1st-release
    init: npm install
    command: npm start

vscode:
  extensions:
    - formulahendry.auto-close-tag@0.5.8:E3l7NRdQytF0+ykejfHKdQ==